// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8cZH8JNiMKfrYYRgCmYMefKXtkqh6Eg',
    appId: '1:964938245079:web:5e89718cf94a88456b6192',
    messagingSenderId: '964938245079',
    projectId: 'finetunedenglish-36df4',
    authDomain: 'finetunedenglish-36df4.firebaseapp.com',
    storageBucket: 'finetunedenglish-36df4.firebasestorage.app',
    measurementId: 'G-N4RFTM0ELY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFifCNla995Qi4zWwIqX1TsBnoVmBOGAM',
    appId: '1:964938245079:android:a89c70283d0456a96b6192',
    messagingSenderId: '964938245079',
    projectId: 'finetunedenglish-36df4',
    storageBucket: 'finetunedenglish-36df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcucs_4nUW05SqJ_mXJXI51eWGKS6zIXg',
    appId: '1:964938245079:ios:2a43b0107f66d8026b6192',
    messagingSenderId: '964938245079',
    projectId: 'finetunedenglish-36df4',
    storageBucket: 'finetunedenglish-36df4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcucs_4nUW05SqJ_mXJXI51eWGKS6zIXg',
    appId: '1:964938245079:ios:2a43b0107f66d8026b6192',
    messagingSenderId: '964938245079',
    projectId: 'finetunedenglish-36df4',
    storageBucket: 'finetunedenglish-36df4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8cZH8JNiMKfrYYRgCmYMefKXtkqh6Eg',
    appId: '1:964938245079:web:6460174870f646bb6b6192',
    messagingSenderId: '964938245079',
    projectId: 'finetunedenglish-36df4',
    authDomain: 'finetunedenglish-36df4.firebaseapp.com',
    storageBucket: 'finetunedenglish-36df4.firebasestorage.app',
    measurementId: 'G-WV92JGXXKW',
  );

}